### ISSUE TITLE
License change to LGPL

### ISSUE THREAD

**Issue by h3xstream** [dotnet-security-guard/roslyn-security-guard#23]
The project is leaving its "experimental" stage.

I am considering changing to the license to LGPL. This will allow the **reuse and integration of the ruleset in external project commercial or not**.
At the same time, I feel the need to **protect the work from being copied in a proprietary project** that is not sharing with the project. The community effort will lose its value if it is systematically copied.

I am opening the discussion. This is not something that needs to be close in a day or two.

I will need the taught of @mcwww and @antmldr since they are previous contributors who have. (Saying that you agree with the change to LGPL will be enough.)

**Comment by mcwww** [comment]
Good for me, you can move forward Phil.

**Comment by antmldr** [comment]
Yep, agreed.
