### ISSUE TITLE
Detect cached authorized pages

### ISSUE THREAD

**Issue by VahidN** [dotnet-security-guard/roslyn-security-guard#32]
Having `OutputCache` will disable the `Authorize` for the next request.

Vulnerable : (should be checked for both action methods and controllers)

```csharp
        [Authorize]  
        [OutputCache]
        public ActionResult ControllerMethod() {

            return null;
        }
```
Solution:

```csharp
        [Authorize]  
        public ActionResult ControllerMethod() {

            return null;
        }
```

Also
Vulnerable : 

```csharp
    [Authorize]
    public class HomeController : Controller
    {
        [OutputCache]        
        public ActionResult Index()
        {
            return View();
        }
    }
```
Solution:
```csharp
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
```

**Comment by h3xstream** [comment]
I just added analyzer to find missing annotation. This will be an easy one.

**Comment by h3xstream** [comment]
@VahidN This is a very interesting behavior. Do you have a reference that explain this behavior?

**Comment by VahidN** [comment]
It's also mentioned as comments in the [AuthorizeAttribute.cs](https://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/AuthorizeAttribute.cs) file too.

**Comment by h3xstream** [comment]
@VahidN Perfect

**Comment by h3xstream** [comment]
@VahidN 
What do you think about the following localisation ?

### Title
OutputCache annotation is disabling authorization checks

### Description
Having the annotation [OutputCache] will disable the annotation [Authorize] for the requests following the first one.

**Comment by VahidN** [comment]
Great :+1:

**Comment by h3xstream** [comment]
I am doing a release shortly that will include this new rule.
