### ISSUE TITLE
Xss prevention analyzer

### ISSUE THREAD

**Issue by Siderale** [dotnet-security-guard/roslyn-security-guard#40]
Working on a rule to prevent, as much as possible, XSS in endpoints.

I Tried to work with the TaintAnalysis to prevent XSS but I didn't succeed - I can't use sinks for endpoints that don't use responses classes (E.g. classes that uses return instead of a HttpResponse)

Implemented a rule that could:
1. Retrieve all the classes that are inheriting from the controller class
2. Retrieve all the methods from this class that are using parameters
3. Retrieve the sensible data from the method with the DataFlowAnalysis
4. Validate that the sensible variables are encoded with a list comparison. 

If they are not, a diagnostic is created.

**Comment by h3xstream** [comment]
@Siderale I am testing the new analyzer there are tons of false positives.

**Comment by Siderale** [comment]
@h3xstream If possible, I'd like to have examples of false positives in order debug the rule. There are still tweaks to do, by example, add encoding methods to the reference list to ensure encoding of sensible data.

**Comment by h3xstream** [comment]
Case 1:
```csharp
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
```
Case 2:
```csharp
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid && WebSecurity.Login(model.UserName, model.Password, persistCookie: model.RememberMe))
            {
                return RedirectToLocal(returnUrl);
            }

            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "The user name or password provided is incorrect.");
            return View(model);
        }
```
Case 3:
```csharp
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                // Attempt to register the user
                try
                {
                    WebSecurity.CreateUserAndAccount(model.UserName, model.Password);
                    WebSecurity.Login(model.UserName, model.Password);
                    return RedirectToAction("Index", "Home");
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("", ErrorCodeToString(e.StatusCode));
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
```

**Comment by h3xstream** [comment]
I would added two conditions before analyzing of the method.
 - Verify that the method is public
 - Verify that the return type is `string`

**Comment by Siderale** [comment]
Great additions, I will work on that today.
