### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by suttonandy** [dotnet-security-guard/roslyn-security-guard#55]
Hi,

I've tried installing this on Visual 2017 RC and the extension does not appear.  I see you only list Visual 2015 under 'Works with' on https://marketplace.visualstudio.com/items?itemName=PhilippeArteau.RoslynSecurityGuard.

My team leader is very keen to use this for our new .NET Core development project.  Do you know when a version for Windows 2017 will be available?  Many thanks.

**Comment by h3xstream** [comment]
I will look at this. It is most likely just a configuration in manifest file.

**Comment by h3xstream** [comment]
I have added Visual Studio 2017 support in the manifest. I have not installed Visual Studio 2017 RC yet.

You can test this dev build:
[RoslynSecurityGuard.Vsix.vsix.zip](https://github.com/dotnet-security-guard/roslyn-security-guard/files/717597/RoslynSecurityGuard.Vsix.vsix.zip)

**Comment by h3xstream** [comment]
The change to the VSIX is here 2a61e9e5c699d6bbe819ee364198c03c96788648

In case you prefer to recompile it yourself, you can use the `master` branch.

**Comment by Mattacks** [comment]
Why do you package it as a .zip?
It just makes installation harder.

**Comment by Mattacks** [comment]
Do you expect the installer to do this?

---------------------------
VSIX Installer
---------------------------
The following extensions are not compatible with Visual Studio 15. Installation may cause Visual Studio to be unstable.

- Roslyn Security Guard

Do you want to continue?
---------------------------
Yes   No   
---------------------------

**Comment by h3xstream** [comment]
@Mattacks 
The zip extension was added because Github does not allow .vsix extension as attachment.

I will install VS 2017 to see what is missing.

**Comment by h3xstream** [comment]
@Mattacks I have migrated the project to VS 2017 and rebuild the extension with the latest VSSDK.

This time it should work without warnings:
https://marketplace.visualstudio.com/items?itemName=PhilippeArteau.RoslynSecurityGuard
