### ISSUE TITLE
VB.NET support

### ISSUE THREAD

**Issue by SJMakin** [dotnet-security-guard/roslyn-security-guard#61]
Great work.  Really like the project - it's like CAT.NET - but done right! 

Please may I request VB.NET support?  I would love to contribute but if this is C# only I cant really invest my time.  Let me know!!

**Comment by h3xstream** [comment]
VB.net is on the road map. The sad part is that the API for Roslyn are completely separated for VB.net and C#.
I am trying to think about the most efficient way to support the symbol execution of both C# and VB.net. Taint analysis is a core component that will always have to be maintain. I want to avoid doubling this task of maintenance.

**Comment by SJMakin** [comment]
VB implemented.  All tests now also test VB and all pass.  Please check out the code and let me know if you want me to change anything.   If you want I will make a pull :)

https://github.com/SJMakin/roslyn-security-guard/tree/VisualBasic/RoslynSecurityGuard

**Comment by h3xstream** [comment]
@SJMakin I have looked at the code. Their seems to a important number of "duplication" but this is impose by the current API. The code seems clear enough to be maintainable.

Yes. You should create a Pull Request. I will looked at it more deeply.

**Comment by DineshManiM** [comment]
Implemented VB support. All tests converted and pass. Please check out the code and let me know if you want me to change anything.

https://github.com/DineshManiM/roslyn-security-guard
