### ISSUE TITLE
Limit the Highlighting of Code for SG0016

### ISSUE THREAD

**Issue by kyleherzog** [dotnet-security-guard/roslyn-security-guard#74]
I'm using VS2017 and when SG0016 is flagged I get the entire function highlighted with the green underline.  This is too much highlighting and makes it hard to see other issues highlighted within the method.  It would be more appropriate to highlight just the method name or return type.

**Comment by h3xstream** [comment]
I had a hard time figuring how to highlight a the first line of the method..
I realized I could simply put the error on one of the attribute preferably the one describing the HTTP verb [HttpPost], [HttpPut], etc.

Here is a preview : 
![csrf](https://user-images.githubusercontent.com/593130/29470810-d1f1e442-841b-11e7-9e2d-9b8ca1535c6d.png)

**Comment by h3xstream** [comment]
Changeset : https://github.com/dotnet-security-guard/roslyn-security-guard/commit/b5f1524ca1e6208126f4043ef2be7fd8cff729be
