### ISSUE TITLE
Limit Highlighting to Just the ValidateInput Attribute for SG0017

### ISSUE THREAD

**Issue by kyleherzog** [dotnet-security-guard/roslyn-security-guard#75]
I'm using VS2017 and when SG0017 is flagged I get the entire function highlighted with the green underline.  This is too much highlighting and makes it hard to see other issues highlighted within the method.  It would be more appropriate to highlight just the ValidateInput(false) attribute.

**Comment by h3xstream** [comment]
I had a hard time figuring how to highlight a the first line of the method..
I realized I could simply put the error on one of the attribute preferably the one describing the HTTP verb [HttpPost], [HttpPut], etc.
![csrf](https://user-images.githubusercontent.com/593130/29470810-d1f1e442-841b-11e7-9e2d-9b8ca1535c6d.png)

**Comment by h3xstream** [comment]
The comment and the code merge actually refer to #74 (similar issue)
