### ISSUE TITLE
Common misconfiguration in Web.config

### ISSUE THREAD

**Issue by h3xstream** [dotnet-security-guard/roslyn-security-guard#8]
Even though Roslyn currently has some limitations[1], it will soon be possible to analyze arbitrary files. We can create some analyzers that will be effective when Roslyn supports the analysis of configuration files.
- [x] Event validation disabled
- [x] View state mac disabled
- [x] Request validation disabled
- [x] View state are not systematically encrypted.

[1] Limitations
- It is not possible to analyze web.config without manual operation. https://github.com/dotnet/roslyn/issues/11097#issuecomment-217972294
- It is not possible to raise an diagnostic warning in additionnal files https://github.com/dotnet/roslyn/issues/6649

**Comment by antmldr** [comment]
Just another idea for a finding: detailed error messages turned on in the resulting web.release.config

**Comment by h3xstream** [comment]
I am closing this ticket.. Additional configuration to watch could be added here : #50
